name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Gatsby project
        uses: actions/checkout@v3
        with:
          # token: ${{ secrets.GH_PAT }}
          submodules: recursive
          repository: aoirint/blog.aoirint.com-gatsby2
          path: '.'

      - name: Clone contents
        uses: actions/checkout@v3
        with:
          # token: ${{ secrets.GH_PAT }}
          submodules: recursive
          repository: aoirint/blog.aoirint.com-contents
          path: 'contents'

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci
 
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ./public
            ./.cache
          key: ${{ runner.os }}-gatsby-build-cache-v1-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-cache-v1-

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.aoirint.com
